spring:
  application:
    name: lms-backend
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api

app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400000

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db
    username: ${DB_USERNAME:lms_user}
    password: ${DB_PASSWORD:lms_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.lms.demo: INFO
    org.springframework.security: DEBUG